### ISSUE TITLE
Examples ekf.step(z) call does return an failure value (=1) - Why?

### ISSUE THREAD

**Issue by bojh** [simondlevy/TinyEKF#11]
Hello I tried to get the Arduino examples working. Started with the Benchmark example - does run OK. Then the SensorFusion example. I have adapted this to the BME280 and mentioned than every cycle ekf.step(z) does return an '1' value which is a failure as read in tiny_ekf.h "caused by non-positive-definite matrix" from (trapped in choldc1()). 
I have checked all, but couldn't find any issue. Then I had a look to the Benchmark example. The result is the same. 
The estimated x values vector does reach their target value after some steps.
I'm not sure what does failure really mean. Is this correct? Is it a real problem - or an bad model?

**Comment by simondlevy** [comment]
Let me know (1) what Arduino you are using (Uno, Due, Teensy, ...) and (2) what BME280 breakout you are using (Sparkfun, Adafruit, ...). Then I can try and reproduce what you've observed.

**Comment by bojh** [comment]
Thanks.  I have tested both sketches (Benchmark and Sensorfusion) on Adafruit Feather nRF52 and on Due. My BME280 is a Amazon cheap 4pin breakout using the Adafruit_BME280 library. As I do not have an analog temperature sensor, so I have first faked the 2. temperature value by:
`    float lm35Temperature = baroTemperature+0.1; //analogRead(LM35_PIN) / 9.31;
` 
and then reduced Mobs=2 with commenting out relevant lines. But never the less the Benchmark sketch is independent from an external input and it also detects a `not positive definite` **a** matrix. I have looked up in the `choles_cpp.txt` source - but looks like correct/same.

**Comment by bojh** [comment]
I did more debugging and found that I have overlooked the inversion at the `TinyEKF::step()` method. 
Sorry for that! Up to what I can see, there is no mistake!
But by the way: A more sophisticated example would be nice to reflect understanding and Kalman filter application use.
Great Thanks.

**Comment by simondlevy** [comment]
Thanks, Joerg!  I was just about to order a BME280 from Amazon, so I'm glad I saw your message first.

I agree, a more sophisticated example would be helpful, but at this point I'm devoting all my free time to other projects.

**Comment by bojh** [comment]
@simondlevy Just for learning and confirmation: 
In your `examples/SensorFusion.ino` you have mentioned a:
```
// A more realistic measurement function would distinguish between state value and measured value; e.g.:
//   hx[0] = pow(this->x[0], 1.03);
//   hx[1] = 1.005 * this->x[1];
//   hx[2] = .9987 * this->x[1] + .001;
```
I have done some learning and simulation with Octave/MATLAB and found a helping source and link:
http://becs.aalto.fi/en/research/bayes/ekfukf/
So finding the Jacabian matrix I have done following:
```
// With octave (pkg load symbolic):
// >> syms x0 x1 a b c d
// >> jacobian([power(x0,1.03), 1.005*x1, 0.9987*x1+0.001],[x0, x1])
// >> jacobian([power(x0,a),        b*x1,      c*x1+d],    [x0, x1])
// we get: 
// ans = (sym 3x2 matrix)
//  [    a   ]
//  [a*x0    ]
//  [-----  0]
//  [  x0    ]
//  [        ]
//  [  0    b]
//  [        ]
//  [  0    c]
```
Can you confirm the correctness of that Jacobian H for your example measurement function?

**Comment by simondlevy** [comment]
I'm sorry, but I don't have the time that it would take to research and give you a helpful answer on this -- too busy teaching :^(
