### ISSUE TITLE
ImportError: No module named realtime_plot

### ISSUE THREAD

**Issue by guglie** [simondlevy/TinyEKF#13]
Thank you for this useful piece of software!
Please make the [RealtimePlotter](https://github.com/simondlevy/RealtimePlotter.git) dependency more evident 😃

**Comment by simondlevy** [comment]
From the README:

In addition to the class definition, the extras/python folder has an example of mouse tracking, using OpenCV. So you will have to install OpenCV to run this example. **There is also a sensor-fusion example in this folder, which uses the RealtimePlotter package, requiring Matplotlib.**

**Comment by guglie** [comment]
Sorry, I missed that!
