### ISSUE TITLE
Help needed in velocity estimation

### ISSUE THREAD

**Issue by Zuputmer** [simondlevy/TinyEKF#18]
Hi,
I am new to kalman filters and this library has proved very useful to me as a stepping stone to learn more about them. I wish to implement the estimation of velocity using this library. I have one sensor giving out only velocity values and another sensor giving me acceleration values. So my model would be-
V(k)=V(k-1)+a.t
A(k)= A(k-1)
However i am unsure where to put this. Does this go in the process model or my measurement function? I am confused and would be grateful if you could help. Thanks.

**Comment by simondlevy** [comment]
I'm pretty sure this would go in the process model, since it does not
involve measurement/observation.
======================

Simon D. Levy
Professor, Computer Science Department
Washington and Lee University
204 W. Washington St.
Lexington, VA 24450

540-458-8419 (voice)
540-458-8255 (fax)

**Comment by Zuputmer** [comment]
@simondlevy thank you very much for your reply. If its not too much trouble, could you kindly explain to me what the process model and measurement functions are (in basic terms) ? 
So i have two states (velocity and acceleration) and two observers (one for each). Considering state 0 to be velocity and state 1 to be acceleration, if i am to put `V(k)=V(k-1)+a.t` in the process model, it would turn out something like this- 
`fx[0]=x[0]+x[1]` and the `Delta T` to be multiplied by the acceleration to derive velocity would go in the process model jacobian like `F[0][1] = 0.00588` . Am i right in doing this ? please correct me if im wrong.
thanks in advance.

**Comment by Zuputmer** [comment]
I think i figured out the first part. this is my code now-
```
class Fuser : public TinyEKF {

    public:

        Fuser()
        {            
            // We approximate the process noise using a small constant
            this->setQ(0, 0, .0001);   //testvals to be altered
            this->setQ(1, 1, .0001);

            // Same for measurement noise - Covariance matrix
            this->setR(0, 0, sq(gpsvals));       //variance of gps- to be calculated at init
            this->setR(1, 1, sq(mpuvals));       //variance of accelerometer - also calc at init
        }

    protected:

        void model(double fx[Nsta], double F[Nsta][Nsta], double hx[Mobs], double H[Mobs][Nsta])
        {
            //Process model is f(x) = x
            fx[0] = (this->x[0] + (this->x[1]*0.00588));         //process model for velocity
            fx[1] = this->x[1];                //process model for acceleration
            
            // So process model Jacobian is identity
            F[0][0] = 1;
            F[1][1] = 1;
            
            hx[0] = this->x[0];                //velocity read by gps
            hx[1] = this->x[0]*3.6;                //acceleration read by IMU
            
            // Jacobian of measurement function
            H[0][0] = 1;        // MPU velocity from previous state
            H[1][1] = 1;        // GPS velocity from previous state
        }
}; 
```
while setting the covariance values, what i'm doing is calculating the mean of the first 1000 values of my gps velocity  and accelerometer output, and squaring them to obtain variance and feeding that to the filter. I have also input delta T in the prediction equation for velocity itself. Thus arise the following doubts-
1) Is `x[0]` the previous value of velocity? Am i right in using this in place of `u` in `v=u+at` ?
2) Once i calculate velocity using the above equation, the output is in m/s. The gps velocity output is in km/h. To convert m/s to km/h i am required to multiply by a factor of `3.6`. Am i right in doing this calculation in hx[1]?

**Comment by ndanilo8** [comment]
did it work? @Zuputmer  I'm trying to implement the same thing
