### ISSUE TITLE
Use library - get matrix 

### ISSUE THREAD

**Issue by sergiosrl** [simondlevy/TinyEKF#2]
Hi, 
I'm looking to correct the position given by my GPS (NEO-M8T) with the use of an IMU. 
How can I get the matrix to use your algorithm?

I tried your example with the temperature readings and worked pretty well, But now I want to fuse two different things.

Best Regards

**Comment by RichardSWheatley** [comment]
Check on a loosely coupled GPS-IMU algorithm.
Then you will see how to apply that information to this matrix.
