### ISSUE TITLE
What is the difference from kalman？

### ISSUE THREAD

**Issue by zihaozhang9** [simondlevy/TinyEKF#21]
Many thanks to the author for contributing the code. But is there any difference between [EKF ](https://github.com/simondlevy/TinyEKF/blob/master/extras/python/tinyekf/__init__.py#L12)and kalman. No jaccsd, no Taylor?

**Comment by massout** [comment]
EKF is an extension of Kalman. Actually, Kalman is for only lineer system models but EKF is "extended" for nonlinear system models. EKF uses Jacobian matrices to solve nonlineerity. In examples of this repo, author is not calculate jacobians so in this repo EKF and KF is the same.

**Comment by zihaozhang9** [comment]
我已收到您发送的邮件。我会及时查看。
