### ISSUE TITLE
possible bug? shouldn't that x[1] be x[2]?

### ISSUE THREAD

**Issue by aguaviva** [simondlevy/TinyEKF#25]
https://github.com/simondlevy/TinyEKF/blob/1a5d6063d8d8eefe4a58b3a2b34858e9ab02a55a/examples/SensorFusion/SensorFusion.ino#L54

Cheers!

**Comment by massout** [comment]
Since the temperature read from LM35 will be combined with the Baro temperature, it should be x[1]. They affecting the same state variable.
