### ISSUE TITLE
How do you adjust the K "Kalman" value

### ISSUE THREAD

**Issue by gizmochief7** [simondlevy/TinyEKF#3]
How do you adjust the K "Kalman" value

**Comment by simondlevy** [comment]
In my code and tutorial I use G for the Kalman gain, which is normally represented as K.  As per the [tutorial](http://home.wlu.edu/~levys/kalman_tutorial/kalman_05.html), this gain is adjusted [automatically](https://github.com/simondlevy/TinyEKF/blob/master/tiny_ekf.c#L328) by the update algorithm.

**Comment by gizmochief7** [comment]
Oh, sorry. I just blindly assumed like other implementations I've used that everything was dynamic except K in order to control the response of the filter to the signal.  I did see that you used G for that but didn't know  how I could publicly control that whether at run-time or setup time.  Do you think it would be possible to add a scaler coefficient to your G value that one could publicly control and  have  that scaler default to 1 or do you think this would mess up other internal calculations. I dont mind adding that myself. More of a question if you think that approach would work cleanly?

**Comment by simondlevy** [comment]
I don't know, and I'm not gonna tinker any more with the code at this point. Good luck.

**Comment by RichardSWheatley** [comment]
You are not supposed to Tinker with the Kalman gain. You can adjust the noise matrices if you wish.

Sent from my iPhone

On Mar 16, 2017, at 23:05, Simon D. Levy <notifications@github.com<mailto:notifications@github.com>> wrote:


I don't know, and I'm not gonna tinker any more with the code at this point. Good luck.
