### ISSUE TITLE
Predicting translation xyz values?

### ISSUE THREAD

**Issue by antithing** [simondlevy/TinyEKF#4]
Hi, thank you for making this code available. I have some sensor measurements that come in at 30Hz. I need to 'upsample' this data to 60Hz, so am looking at the kalman filter to predict the measurements in between the samples.  Is your filter suitable for this? If you have a minute, would you be able to point me in the right direction to do this using your code? Thank you!

**Comment by RichardSWheatley** [comment]
For each sensor, the prediction is based upon the previous measurement and the measured noise in the measurement. You can use the EKF as a smoother that accepts only individual sensor data.

Typically the smoothers would have an Identity Matrix for the transformation matrix.
This would make the estimation simply the old EKF filtered value simply add a bit of noise.

Go to https://github.com/simondlevy/TinyEKF/blob/master/examples/SensorFusion/SensorFusion.ino to see how this is done.

**Comment by fangchen1993** [comment]
Hi, thank you for making this code available.I'm a student from China.I don't know the method that you use.It is  quaternion or euler angle?And i have a STM32  Development Board.How i can use your code to test my sensors(imu gps and magnetometer)?Looking forward to your reply！Thank you!
