### ISSUE TITLE
Does the Jacobian get updated?

### ISSUE THREAD

**Issue by gosila** [simondlevy/TinyEKF#9]
Thank you for making the awesome tutorial and code available.

Question in the python sample code.

https://github.com/simondlevy/TinyEKF/blob/master/python/tinyekf/__init__.py

Why getH(x) and getF(x) are only called once during the init? Shouldn't them be updated each step()?

**Comment by simondlevy** [comment]
Good call, gosila!  I've modified the Python library and examples to do this correctly.
